
'------------------------------------------------------------------------------
' <auto-generated>
'    此代码是根据模板生成的。
'
'    手动更改此文件可能会导致应用程序中发生异常行为。
'    如果重新生成代码，则将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("e5919477-ddd1-42ce-8409-a7089391b2b9")>

#Region "上下文"

''' <summary>
''' 没有元数据文档可用。
''' </summary>
Public Partial Class testEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' 请使用应用程序配置文件的“testEntities”部分中的连接字符串初始化新 testEntities 对象。
    ''' </summary>
    Public Sub New()
        MyBase.New("name=testEntities", "testEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' 初始化新的 testEntities 对象。
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "testEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' 初始化新的 testEntities 对象。
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "testEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

End Class

#End Region

